/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.BorderFactory;

/**
 *
 * @author Familia
 */
public class Administrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        BuscarCategoria = new javax.swing.JButton();
        BuscarNombre = new javax.swing.JButton();
        BuscarCodigo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        jLabel1.setText("BUSCAR LIBROS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("POR CATEGORIA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("POR CODIGO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("POR NOMBRE");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FICCION", "AVENTURA", "CIENCIA", "INGENIERIA", " " }));

        BuscarCategoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BuscarCategoria.setText("BUSCAR");
        BuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCategoriaActionPerformed(evt);
            }
        });

        BuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BuscarNombre.setText("BUSCAR");
        BuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNombreActionPerformed(evt);
            }
        });

        BuscarCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BuscarCodigo.setText("BUSCAR");
        BuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuscarNombre)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(BuscarCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCodigo))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarCategoria)
                    .addComponent(BuscarNombre)
                    .addComponent(BuscarCodigo))
                .addContainerGap())
        );

        jTabbedPane1.addTab("NAVEGAR EN LA BIBLIOTECA", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CREAR UN LIBRO", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCategoriaActionPerformed

	
		// TODO add your handling code here:
        // El JFrame con el JDesktopPane
		JFrame ventana = new JFrame("LIBROS POR CATEGORIA");
                //creamos el desktop panel
		JDesktopPane dp = new JDesktopPane();
                // lo metemos en lel frame
		ventana.getContentPane().add(dp);
		
	//panel parte superior de la ventana 
		JPanel arriba = new JPanel(new FlowLayout());
                //titulo de la subventana
		arriba.add (new JLabel("LIBROS ENCONTRADOS"));
        //panel parte media de la ventana
                JPanel medio=new JPanel(new FlowLayout());
                //aqui ira la lista de libros que nos pasen
		JList lista=new JList();
                DefaultListModel modelo = new DefaultListModel();
                //ejemplo de como agregar un elemento a la lista (hay que hacerlo con los nombres de los libros
                modelo.addElement("hola");
                lista.setModel(modelo);
                //agregamos nuestra lista al panel del medio
                medio.add(lista);
                
         //creamos un panel inferior donde pondremos el boton de consultar libro       
                JPanel inferior=new JPanel(new FlowLayout());
                //creamos el boton
                JButton elegir= new JButton("consultar");
                //lo metemos al panel inferior
                inferior.add(elegir);
                
                
                
                        
                
		
		// Se construye el JInternalFrame
		JInternalFrame internal = new JInternalFrame("Un Internal Frame");
		
                //se meten los paneles dentro del internal frame
                
                internal.getContentPane().add(arriba,BorderLayout.NORTH);
                internal.getContentPane().add(inferior,BorderLayout.SOUTH);
                internal.getContentPane().add(medio,BorderLayout.CENTER);

		
		// Es importante darle tamaño -pack()- al JInternalFrame,
		// porque si no, tendrá tamaño 0,0 y no lo veremos.
		internal.setSize(490, 470);
		
		// Por defecto el JInternalFrame no es redimensionable ni
		// tiene el botón de cerrar, así que se lo ponemos.
		internal.setResizable(true);
		internal.setClosable(true);
		
		// Se mete el internal en el JDesktopPane
		dp.add(internal);
		
		// Se visualiza todo.
		ventana.setSize(500,500);
		ventana.setVisible(true);
		ventana.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		// Se visualiza el JInternalFrame 
		internal.setVisible(true);
	

      // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCategoriaActionPerformed

    private void BuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNombreActionPerformed
        // TODO add your handling code here:
        // El JFrame con el JDesktopPane
		JFrame ventana = new JFrame("LIBROS POR CATEGORIA");
                //creamos el desktop panel
		JDesktopPane dp = new JDesktopPane();
                // lo metemos en lel frame
		ventana.getContentPane().add(dp);
		
	//panel parte superior de la ventana 
		JPanel arriba = new JPanel(new FlowLayout());
                //titulo de la subventana
		arriba.add (new JLabel("LIBROS ENCONTRADOS"));
        //panel parte media de la ventana
                JPanel medio=new JPanel(new FlowLayout());
                //aqui ira la lista de libros que nos pasen
		JList lista=new JList();
                DefaultListModel modelo = new DefaultListModel();
                //ejemplo de como agregar un elemento a la lista (hay que hacerlo con los nombres de los libros
                modelo.addElement("hola");
                lista.setModel(modelo);
                //agregamos nuestra lista al panel del medio
                medio.add(lista);
                
         //creamos un panel inferior donde pondremos el boton de consultar libro       
                JPanel inferior=new JPanel(new FlowLayout());
                //creamos el boton
                JButton elegir= new JButton("consultar");
                //lo metemos al panel inferior
                inferior.add(elegir);
                
                
                
                        
                
		
		// Se construye el JInternalFrame
		JInternalFrame internal = new JInternalFrame("Un Internal Frame");
		
                //se meten los paneles dentro del internal frame
                
                internal.getContentPane().add(arriba,BorderLayout.NORTH);
                internal.getContentPane().add(inferior,BorderLayout.SOUTH);
                internal.getContentPane().add(medio,BorderLayout.CENTER);

		
		// Es importante darle tamaño -pack()- al JInternalFrame,
		// porque si no, tendrá tamaño 0,0 y no lo veremos.
		internal.setSize(490, 470);
		
		// Por defecto el JInternalFrame no es redimensionable ni
		// tiene el botón de cerrar, así que se lo ponemos.
		internal.setResizable(true);
		internal.setClosable(true);
		
		// Se mete el internal en el JDesktopPane
		dp.add(internal);
		
		// Se visualiza todo.
		ventana.setSize(500,500);
		ventana.setVisible(true);
		ventana.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		// Se visualiza el JInternalFrame 
		internal.setVisible(true);
	

    }//GEN-LAST:event_BuscarNombreActionPerformed

    private void BuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCodigoActionPerformed
        // TODO add your handling code here:
        // El JFrame con el JDesktopPane
		JFrame ventana = new JFrame("LIBROS POR CATEGORIA");
                //creamos el desktop panel
		JDesktopPane dp = new JDesktopPane();
                // lo metemos en lel frame
		ventana.getContentPane().add(dp);
		
	//panel parte superior de la ventana 
		JPanel arriba = new JPanel(new FlowLayout());
                //titulo de la subventana
		arriba.add (new JLabel("LIBROS ENCONTRADOS"));
        //panel parte media de la ventana
                JPanel medio=new JPanel(new FlowLayout());
                //aqui ira la lista de libros que nos pasen
		JList lista=new JList();
                DefaultListModel modelo = new DefaultListModel();
                //ejemplo de como agregar un elemento a la lista (hay que hacerlo con los nombres de los libros
                modelo.addElement("hola");
                lista.setModel(modelo);
                //agregamos nuestra lista al panel del medio
                medio.add(lista);
                
         //creamos un panel inferior donde pondremos el boton de consultar libro       
                JPanel inferior=new JPanel(new FlowLayout());
                //creamos el boton
                JButton elegir= new JButton("consultar");
                //lo metemos al panel inferior
                inferior.add(elegir);
                
                
                
                        
                
		
		// Se construye el JInternalFrame
		JInternalFrame internal = new JInternalFrame("Un Internal Frame");
		
                //se meten los paneles dentro del internal frame
                
                internal.getContentPane().add(arriba,BorderLayout.NORTH);
                internal.getContentPane().add(inferior,BorderLayout.SOUTH);
                internal.getContentPane().add(medio,BorderLayout.CENTER);

		
		// Es importante darle tamaño -pack()- al JInternalFrame,
		// porque si no, tendrá tamaño 0,0 y no lo veremos.
		internal.setSize(490, 470);
		
		// Por defecto el JInternalFrame no es redimensionable ni
		// tiene el botón de cerrar, así que se lo ponemos.
		internal.setResizable(true);
		internal.setClosable(true);
		
		// Se mete el internal en el JDesktopPane
		dp.add(internal);
		
		// Se visualiza todo.
		ventana.setSize(500,500);
		ventana.setVisible(true);
		ventana.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		// Se visualiza el JInternalFrame 
		internal.setVisible(true);
	

    }//GEN-LAST:event_BuscarCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCategoria;
    private javax.swing.JButton BuscarCodigo;
    private javax.swing.JButton BuscarNombre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables


/*public PruebaInternalFrame()
	{
		// El JFrame con el JDesktopPane
		JFrame v = new JFrame("Prueba JInternalFrame");
		JDesktopPane dp = new JDesktopPane();
		v.getContentPane().add(dp);
		
		// Se construye el panel que ira dentro del JInternalFrame
		JPanel p = new JPanel();
		p.setLayout(new FlowLayout());
		p.add (new JLabel("Una etiqueta"));
		p.add (new JTextField(10));
		
		// Se construye el JInternalFrame
		JInternalFrame internal = new JInternalFrame("Un Internal Frame");
		internal.add(p);
		
		// Es importante darle tamaño -pack()- al JInternalFrame,
		// porque si no, tendrá tamaño 0,0 y no lo veremos.
		internal.pack();
                
		
		// Por defecto el JInternalFrame no es redimensionable ni
		// tiene el botón de cerrar, así que se lo ponemos.
		internal.setResizable(true);
		internal.setClosable(true);
		
		// Se mete el internal en el JDesktopPane
		dp.add(internal);
		
		// Se visualiza todo.
		v.setSize(500,500);
		v.setVisible(true);
		v.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		// Se visualiza el JInternalFrame 
		internal.setVisible(true);
	}*/

}