/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import tipografia.*;

/**
 *
 * @author JhonCarlos
 */
public class AgregarRecarga extends javax.swing.JFrame {
    Fuente verdanaRegular, verdanaBold, garamondRegular;

    /**
     * Creates new form AgregarRecarga
     */
    public AgregarRecarga() {
        initComponents();
        
        //Posición
        this.setLocationRelativeTo(null);
        
        this.verdanaRegular = new Fuente(4);
        this.verdanaBold = new Fuente(5);
        this.garamondRegular = new Fuente(3);
        
        this.jLabelIndMacro5.setFont(garamondRegular.fuenteAgregar(18f));
        this.jLabelInd10.setFont(verdanaBold.fuenteAgregar(12f));
        this.jTextFieldSaldo.setFont(verdanaRegular.fuenteAgregar(12f));
        
        this.jButtonAgregarRecarga.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jButtonCancelar.setFont(verdanaRegular.fuenteAgregar(12f));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButtonMinimizarUL = new javax.swing.JButton();
        jButtonCerrarUL = new javax.swing.JButton();
        jLabelIndMacro5 = new javax.swing.JLabel();
        jLabelInd10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAgregarRecarga = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(69, 54, 55));

        jPanel2.setBackground(new java.awt.Color(69, 54, 55));

        jButtonMinimizarUL.setBackground(new java.awt.Color(69, 54, 55));
        jButtonMinimizarUL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonMinimizarUL.setForeground(new java.awt.Color(201, 178, 169));
        jButtonMinimizarUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MinimizarUL.png"))); // NOI18N
        jButtonMinimizarUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarULActionPerformed(evt);
            }
        });

        jButtonCerrarUL.setBackground(new java.awt.Color(69, 54, 55));
        jButtonCerrarUL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonCerrarUL.setForeground(new java.awt.Color(201, 178, 169));
        jButtonCerrarUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CerrarUL.png"))); // NOI18N
        jButtonCerrarUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarULActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMinimizarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCerrarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCerrarUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonMinimizarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelIndMacro5.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jLabelIndMacro5.setForeground(new java.awt.Color(229, 229, 229));
        jLabelIndMacro5.setText("Nueva Recarga");

        jLabelInd10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd10.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd10.setText("Saldo:");

        jPanel3.setBackground(new java.awt.Color(69, 54, 55));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jButtonAgregarRecarga.setBackground(new java.awt.Color(69, 54, 55));
        jButtonAgregarRecarga.setForeground(new java.awt.Color(229, 229, 229));
        jButtonAgregarRecarga.setText("Agregar Recarga");
        jButtonAgregarRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRecargaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregarRecarga);

        jButtonCancelar.setBackground(new java.awt.Color(69, 54, 55));
        jButtonCancelar.setForeground(new java.awt.Color(229, 229, 229));
        jButtonCancelar.setText("Cancelar Recarga");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancelar);

        jTextFieldSaldo.setBackground(new java.awt.Color(69, 54, 55));
        jTextFieldSaldo.setForeground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIndMacro5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSaldo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndMacro5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInd10)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizarULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarULActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarULActionPerformed

    private void jButtonCerrarULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarULActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarULActionPerformed

    private void jButtonAgregarRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRecargaActionPerformed
        // TODO add your handling code here:
        String msjRecarga = "¿Está seguro de recargar " + this.jTextFieldSaldo.getText() + " a su cuenta?";
        int modificar = JOptionPane.showConfirmDialog(this, msjRecarga, "Seleccione una opción.", JOptionPane.YES_NO_OPTION);

        if(JOptionPane.OK_OPTION == modificar){
            this.dispose();
            JOptionPane.showMessageDialog(this, "La recarga se realizó exitosamente.");
        }else{
            JOptionPane.showMessageDialog(this, "Recarga no realizada.");
        }
    }//GEN-LAST:event_jButtonAgregarRecargaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        int modificar = JOptionPane.showConfirmDialog(this, "¿Está seguro de cancelar la recarga?", "Seleccione una opción.", JOptionPane.YES_NO_OPTION);

        if(JOptionPane.OK_OPTION == modificar){
            this.dispose();
            JOptionPane.showMessageDialog(this, "Recarga cancelada.");
        }/*else{

        } */
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarRecarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarRecarga;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCerrarUL;
    private javax.swing.JButton jButtonMinimizarUL;
    private javax.swing.JLabel jLabelInd10;
    private javax.swing.JLabel jLabelIndMacro5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
