/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import tipografia.*;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
/**
 *
 * @author JhonCarlos
 */
public class Login extends javax.swing.JFrame {
    
    //Variables de posición
    int x,y;

    /**
     * Creates new form InicioSesion
     */
    public Login() {
        initComponents();
        
        //Posición
        this.setLocationRelativeTo(null);
        
        //Forma redondeada
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,27,27);
        AWTUtilities.setWindowShape(this, forma);
        
        //Cargar fuentes
        Fuente garamondBoldItalic = new Fuente(1);
        Fuente garamondPlain = new Fuente(3);
        Fuente garamondBold = new Fuente(0);
        
        //Establecer fuentes
        this.jLabelTitulo0.setFont(garamondBoldItalic.fuenteAgregar(36f));
        this.jLabelTitulo1.setFont(garamondPlain.fuenteAgregar(24f));
        this.jLabelUsuario.setFont(garamondBold.fuenteAgregar(20f));
        this.jLabelPassword.setFont(garamondBold.fuenteAgregar(20f));
        
    }
    
    //Colocar icono en barra de tareas.
    public Image getIconImage(){
        Image refValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo Reducido.png"));
        return refValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMinimizar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabelTitulo0 = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonIngreso = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMinimizar.setBackground(new java.awt.Color(63, 36, 36));
        jButtonMinimizar.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jButtonMinimizar.setForeground(new java.awt.Color(187, 174, 167));
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MinimizarUL.png"))); // NOI18N
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 30));

        jButtonCerrar.setBackground(new java.awt.Color(63, 36, 36));
        jButtonCerrar.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(187, 174, 167));
        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CerrarUL.png"))); // NOI18N
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 10, 40, 30));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Reducido.png"))); // NOI18N
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 230));

        jLabelTitulo0.setFont(new java.awt.Font("Adobe Garamond Pro", 3, 36)); // NOI18N
        jLabelTitulo0.setForeground(new java.awt.Color(187, 174, 167));
        jLabelTitulo0.setText("La Weblioteca");
        getContentPane().add(jLabelTitulo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 270, 30));

        jLabelTitulo1.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 24)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(187, 174, 167));
        jLabelTitulo1.setText("Sí, con libros y eso.");
        getContentPane().add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 20)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(187, 174, 167));
        jLabelUsuario.setText("Usuario: ");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 20)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(187, 174, 167));
        jLabelPassword.setText("Contraseña: ");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(63, 36, 36));
        jTextFieldUsuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(187, 174, 167));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 180, -1));

        jPassword.setBackground(new java.awt.Color(63, 36, 36));
        jPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(187, 174, 167));
        jPassword.setText("jPasswordField1");
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 180, -1));

        jButtonIngreso.setBackground(new java.awt.Color(63, 36, 36));
        jButtonIngreso.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 14)); // NOI18N
        jButtonIngreso.setForeground(new java.awt.Color(187, 174, 167));
        jButtonIngreso.setText("Iniciar Sesión");
        getContentPane().add(jButtonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 290, 30));

        jButton1.setText("Escritorio UL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, -1));

        jButton2.setText("Escritorio UAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 140, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Inicio.jpg"))); // NOI18N
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 581));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UL objUL = new UL();
        objUL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UAL objUAL = new UAL();
        objUAL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jLabelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseClicked
        // TODO add your handling code here:
        // Para recibir coordenadas de posición de ventana.
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabelFondoMouseClicked

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
        // TODO add your handling code here:
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x-x,p.y-y);
    }//GEN-LAST:event_jLabelFondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonIngreso;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTitulo0;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
