/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author JhonCarlos
 */
public class SugerenciasLibros extends javax.swing.JPanel {

    /**
     * Creates new form SugerenciasLibros
     */
    public SugerenciasLibros() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryBook1 = new vista.SummaryBook();
        summaryBook2 = new vista.SummaryBook();
        summaryBook3 = new vista.SummaryBook();
        summaryBook4 = new vista.SummaryBook();

        setLayout(new java.awt.GridLayout(1, 7, 0, 10));
        add(summaryBook1);
        add(summaryBook2);
        add(summaryBook3);
        add(summaryBook4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.SummaryBook summaryBook1;
    private vista.SummaryBook summaryBook2;
    private vista.SummaryBook summaryBook3;
    private vista.SummaryBook summaryBook4;
    // End of variables declaration//GEN-END:variables
}
