/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import tipografia.*;

import java.awt.Color;

/**
 *
 * @author JhonCarlos
 */

public class SummaryBook extends javax.swing.JPanel {
    
    Color transparencia;

    /**
     * Creates new form SummaryBook
     */
    public SummaryBook() {
        initComponents();
        this.transparencia = new Color(0,0,0,0);
        this.setBackground(transparencia);
        this.jPanelContenedorPortada.setBackground(transparencia);
        this.jPanelContenedorInfo.setBackground(transparencia);
        this.jPanelPortada.setBackground(transparencia);
        
        //Cargar fuentes
        Fuente garamondItalic = new Fuente(2);
        Fuente garamondRegular = new Fuente(3);
        Fuente verdanaRegular = new Fuente(4);
        
        //Establecer fuentes
        this.jLabelTitulo.setFont(garamondItalic.fuenteAgregar(18f));
        this.jLabelAutor.setFont(garamondRegular.fuenteAgregar(16f));
        this.jLabelSinopsis.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jButtonVerMas.setFont(verdanaRegular.fuenteAgregar(12f));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedorPortada = new javax.swing.JPanel();
        jPanelPortada = new javax.swing.JPanel();
        jPanelContenedorInfo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jButtonVerMas = new javax.swing.JButton();
        jLabelSinopsis = new javax.swing.JLabel();
        jLabelEstrella1 = new javax.swing.JLabel();
        jLabelEstrella2 = new javax.swing.JLabel();
        jLabelEstrella3 = new javax.swing.JLabel();
        jLabelEstrella4 = new javax.swing.JLabel();
        jLabelEstrella5 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanelContenedorPortada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(69, 60, 70), new java.awt.Color(69, 60, 70)));

        jPanelPortada.setBackground(new java.awt.Color(69, 54, 55));

        javax.swing.GroupLayout jPanelPortadaLayout = new javax.swing.GroupLayout(jPanelPortada);
        jPanelPortada.setLayout(jPanelPortadaLayout);
        jPanelPortadaLayout.setHorizontalGroup(
            jPanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanelPortadaLayout.setVerticalGroup(
            jPanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelContenedorPortadaLayout = new javax.swing.GroupLayout(jPanelContenedorPortada);
        jPanelContenedorPortada.setLayout(jPanelContenedorPortadaLayout);
        jPanelContenedorPortadaLayout.setHorizontalGroup(
            jPanelContenedorPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorPortadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContenedorPortadaLayout.setVerticalGroup(
            jPanelContenedorPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorPortadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanelContenedorPortada);

        jPanelContenedorInfo.setBackground(new java.awt.Color(69, 54, 55));

        jLabelTitulo.setFont(new java.awt.Font("Adobe Garamond Pro", 2, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(229, 229, 229));
        jLabelTitulo.setText("(Titulo)");

        jLabelAutor.setForeground(new java.awt.Color(206, 206, 206));
        jLabelAutor.setText("(Autor)");

        jButtonVerMas.setBackground(new java.awt.Color(69, 54, 55));
        jButtonVerMas.setForeground(new java.awt.Color(177, 177, 177));
        jButtonVerMas.setText("Ver Más...");

        jLabelSinopsis.setForeground(new java.awt.Color(177, 177, 177));
        jLabelSinopsis.setText("(Sinopsis)");

        jLabelEstrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaLlena.png"))); // NOI18N

        jLabelEstrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaLlena.png"))); // NOI18N

        jLabelEstrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaLlena.png"))); // NOI18N

        jLabelEstrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaVacia.png"))); // NOI18N

        jLabelEstrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaVacia.png"))); // NOI18N

        javax.swing.GroupLayout jPanelContenedorInfoLayout = new javax.swing.GroupLayout(jPanelContenedorInfo);
        jPanelContenedorInfo.setLayout(jPanelContenedorInfoLayout);
        jPanelContenedorInfoLayout.setHorizontalGroup(
            jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerMas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContenedorInfoLayout.createSequentialGroup()
                        .addGroup(jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelAutor)
                            .addGroup(jPanelContenedorInfoLayout.createSequentialGroup()
                                .addComponent(jLabelEstrella1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella5)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelContenedorInfoLayout.setVerticalGroup(
            jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabelAutor)
                .addGap(26, 26, 26)
                .addGroup(jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelContenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEstrella1)
                            .addComponent(jLabelEstrella2))
                        .addComponent(jLabelEstrella4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelEstrella5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelEstrella3))
                .addGap(18, 18, 18)
                .addComponent(jLabelSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVerMas)
                .addContainerGap())
        );

        add(jPanelContenedorInfo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerMas;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEstrella1;
    private javax.swing.JLabel jLabelEstrella2;
    private javax.swing.JLabel jLabelEstrella3;
    private javax.swing.JLabel jLabelEstrella4;
    private javax.swing.JLabel jLabelEstrella5;
    private javax.swing.JLabel jLabelSinopsis;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenedorInfo;
    private javax.swing.JPanel jPanelContenedorPortada;
    private javax.swing.JPanel jPanelPortada;
    // End of variables declaration//GEN-END:variables
}
