/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import tipografia.*;

import java.awt.Color;
import java.awt.Point;
import javax.swing.*;

/**
 *
 * @author JhonCarlos
 */
public class SummaryLastBook extends javax.swing.JPanel {
    Color transparencia;
    Fuente garamondRegular, garamondItalic, verdanaRegular, verdanaBold;

    /**
     * Creates new form SummaryLastBook
     */
    public SummaryLastBook() {
        initComponents();
         
        this.transparencia = new Color(0,0,0,0);
        this.garamondRegular = new Fuente(3);
        this.garamondItalic = new Fuente(2);
        this.verdanaRegular = new Fuente(4);
        this.verdanaBold = new Fuente(5);
        
        this.setBackground(transparencia);
        //this.jPanelPortada.setBackground(transparencia);
        this.jPanelInfo.setBackground(transparencia);
        this.jPanel1.setBackground(transparencia);
        this.establecerMedidas();
        
        //Centrar imagen de portada
        this.jLabelPortada.setHorizontalAlignment(SwingConstants.CENTER);
        this.jLabelPortada.setVerticalAlignment(SwingConstants.CENTER);
        
        //Establecer fuentes
        this.jLabelTitulo.setFont(garamondItalic.fuenteAgregar(18f));
        this.jLabelTitulo2.setFont(garamondRegular.fuenteAgregar(16f));
        this.jLabelAutor.setFont(verdanaRegular.fuenteAgregar(14f));
        this.jLabelInd1.setFont(verdanaBold.fuenteAgregar(14f));
        this.jLabelInd2.setFont(verdanaBold.fuenteAgregar(14f));
        this.jButtonListaLibros.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jButtonContinuarLectura.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jButtonInfoBook.setFont(verdanaRegular.fuenteAgregar(12f));
        
    }
    
    public void establecerMedidas(){
        int anchuraPortada = (int) Math.floor((this.getWidth() * 2/5) - 20);
        int anchuraInfo = (int) Math.floor((this.getWidth() * 3/5) - 10);
        int altura = (int) Math.floor(this.getHeight() - 20);
        Point pPortada = new Point(10,10);
        Point pInfo = new Point(anchuraPortada + 20, 10);
        
        this.jPanelPortada.setSize(anchuraPortada, altura);
        this.jPanelPortada.setLocation(pPortada);
        this.jPanelInfo.setLocation(pInfo);
        this.jPanelInfo.setSize(anchuraInfo, altura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPortada = new javax.swing.JPanel();
        jLabelPortada = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelPorcentajeLectura = new javax.swing.JLabel();
        jButtonListaLibros = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonContinuarLectura = new javax.swing.JButton();
        jButtonInfoBook = new javax.swing.JButton();
        jLabelInd1 = new javax.swing.JLabel();
        jLabelInd2 = new javax.swing.JLabel();
        jLabelEstrella1 = new javax.swing.JLabel();
        jLabelEstrella2 = new javax.swing.JLabel();
        jLabelEstrella3 = new javax.swing.JLabel();
        jLabelEstrella4 = new javax.swing.JLabel();
        jLabelEstrella5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(69, 54, 55));

        jPanelPortada.setBackground(new java.awt.Color(79, 79, 79));

        javax.swing.GroupLayout jPanelPortadaLayout = new javax.swing.GroupLayout(jPanelPortada);
        jPanelPortada.setLayout(jPanelPortadaLayout);
        jPanelPortadaLayout.setHorizontalGroup(
            jPanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanelPortadaLayout.setVerticalGroup(
            jPanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelInfo.setBackground(new java.awt.Color(102, 102, 102));

        jLabelTitulo.setBackground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setFont(new java.awt.Font("Adobe Garamond Pro", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(229, 229, 229));
        jLabelTitulo.setText("(Título)");

        jLabelTitulo2.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 16)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(229, 229, 229));
        jLabelTitulo2.setText("(Título 2)");

        jLabelAutor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(229, 229, 229));
        jLabelAutor.setText("(Autor)");

        jLabelPorcentajeLectura.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelPorcentajeLectura.setForeground(new java.awt.Color(229, 229, 229));
        jLabelPorcentajeLectura.setText("(Porcentaje de lectura)");

        jButtonListaLibros.setBackground(new java.awt.Color(69, 54, 55));
        jButtonListaLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonListaLibros.setForeground(new java.awt.Color(229, 229, 229));
        jButtonListaLibros.setText("Mi Biblioteca");

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jButtonContinuarLectura.setBackground(new java.awt.Color(69, 54, 55));
        jButtonContinuarLectura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonContinuarLectura.setForeground(new java.awt.Color(229, 229, 229));
        jButtonContinuarLectura.setText("Continuar Lectura");
        jButtonContinuarLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarLecturaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonContinuarLectura);

        jButtonInfoBook.setBackground(new java.awt.Color(69, 54, 55));
        jButtonInfoBook.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonInfoBook.setForeground(new java.awt.Color(229, 229, 229));
        jButtonInfoBook.setText("Ver información del Libro");
        jButtonInfoBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoBookActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInfoBook);

        jLabelInd1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelInd1.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd1.setText("% Lectura:");

        jLabelInd2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelInd2.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd2.setText("Calificación:");

        jLabelEstrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaLlena.png"))); // NOI18N

        jLabelEstrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaLlena.png"))); // NOI18N

        jLabelEstrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaLlena.png"))); // NOI18N

        jLabelEstrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaVacia.png"))); // NOI18N

        jLabelEstrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EstrellaVacia.png"))); // NOI18N

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jButtonListaLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelTitulo2)
                            .addGroup(jPanelInfoLayout.createSequentialGroup()
                                .addComponent(jLabelInd2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEstrella1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstrella5))
                            .addGroup(jPanelInfoLayout.createSequentialGroup()
                                .addComponent(jLabelInd1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPorcentajeLectura)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo2)
                .addGap(18, 18, 18)
                .addComponent(jLabelAutor)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInd1)
                            .addComponent(jLabelPorcentajeLectura))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInd2))
                    .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEstrella1)
                            .addComponent(jLabelEstrella2))
                        .addComponent(jLabelEstrella4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelEstrella5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelEstrella3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListaLibros))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInfoBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoBookActionPerformed
        // TODO add your handling code here:
        InfoBook objInfoBook = new InfoBook();
        objInfoBook.setVisible(true);
    }//GEN-LAST:event_jButtonInfoBookActionPerformed

    private void jButtonContinuarLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarLecturaActionPerformed
        // TODO add your handling code here:
        Lectura objLectura = new Lectura();
        objLectura.setVisible(true);
    }//GEN-LAST:event_jButtonContinuarLecturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonContinuarLectura;
    public javax.swing.JButton jButtonInfoBook;
    public javax.swing.JButton jButtonListaLibros;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEstrella1;
    private javax.swing.JLabel jLabelEstrella2;
    private javax.swing.JLabel jLabelEstrella3;
    private javax.swing.JLabel jLabelEstrella4;
    private javax.swing.JLabel jLabelEstrella5;
    private javax.swing.JLabel jLabelInd1;
    private javax.swing.JLabel jLabelInd2;
    private javax.swing.JLabel jLabelPorcentajeLectura;
    private javax.swing.JLabel jLabelPortada;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelPortada;
    // End of variables declaration//GEN-END:variables
}
