/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.*;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author JhonCarlos
 */
public class UL extends javax.swing.JFrame {
    //Ejecutable ejec;
    Color transparencia;

    /**
     * Creates new form UL
     */
    public UL() {
        initComponents();
        /*
        this.setTitle("Bienvenido, ."); // Añadir nombre de usuario.
        try {
            ejec = new Ejecutable();
        } catch (IOException ex) {
            Logger.getLogger(UL.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ha ocurrido un error y no fue posible abrir el programa. Inténtelo de nuevo más tarde.");
        }
        */
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        
        //Correcciones de color
        this.transparencia = new Color(0,0,0,00);
        jDesktopPane1.setBorder(new Background(0));
        this.contenedorSup.setBackground(transparencia);
        this.contenedorInf.setBackground(transparencia);
        this.jPanelSummaryLastBook.setBackground(transparencia);
        this.jPanelSummaryUser.setBackground(transparencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryBook1 = new vista.SummaryBook();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonMinimizarUL = new javax.swing.JButton();
        jButtonCerrarUL = new javax.swing.JButton();
        contenedorPrincipal = new vista.TransparentPanel();
        contenedorSup = new javax.swing.JPanel();
        jPanelSummaryUser = new javax.swing.JPanel();
        summaryUserUL1 = new vista.SummaryUserUL();
        jPanelSummaryLastBook = new javax.swing.JPanel();
        summaryLastBook1 = new vista.SummaryLastBook();
        contenedorInf = new javax.swing.JScrollPane();
        sugerenciasLibros1 = new vista.SugerenciasLibros();
        jButtonUsuario = new javax.swing.JButton();
        jButtonBiblioteca = new javax.swing.JButton();
        jButtonTienda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(69, 54, 55));

        jButtonCerrarSesion.setBackground(new java.awt.Color(69, 54, 55));
        jButtonCerrarSesion.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonCerrarSesion.setForeground(new java.awt.Color(201, 178, 169));
        jButtonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BotonCSesionUL.png"))); // NOI18N
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonMinimizarUL.setBackground(new java.awt.Color(69, 54, 55));
        jButtonMinimizarUL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonMinimizarUL.setForeground(new java.awt.Color(201, 178, 169));
        jButtonMinimizarUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MinimizarUL.png"))); // NOI18N
        jButtonMinimizarUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarULActionPerformed(evt);
            }
        });

        jButtonCerrarUL.setBackground(new java.awt.Color(69, 54, 55));
        jButtonCerrarUL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonCerrarUL.setForeground(new java.awt.Color(201, 178, 169));
        jButtonCerrarUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CerrarUL.png"))); // NOI18N
        jButtonCerrarUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarULActionPerformed(evt);
            }
        });

        contenedorPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(69, 60, 70), new java.awt.Color(69, 60, 70)));
        contenedorPrincipal.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        contenedorSup.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanelSummaryUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(69, 60, 70), new java.awt.Color(69, 60, 70)));

        javax.swing.GroupLayout jPanelSummaryUserLayout = new javax.swing.GroupLayout(jPanelSummaryUser);
        jPanelSummaryUser.setLayout(jPanelSummaryUserLayout);
        jPanelSummaryUserLayout.setHorizontalGroup(
            jPanelSummaryUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSummaryUserLayout.createSequentialGroup()
                .addComponent(summaryUserUL1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSummaryUserLayout.setVerticalGroup(
            jPanelSummaryUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(summaryUserUL1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        contenedorSup.add(jPanelSummaryUser);

        jPanelSummaryLastBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(69, 60, 70), new java.awt.Color(69, 60, 70)));

        javax.swing.GroupLayout jPanelSummaryLastBookLayout = new javax.swing.GroupLayout(jPanelSummaryLastBook);
        jPanelSummaryLastBook.setLayout(jPanelSummaryLastBookLayout);
        jPanelSummaryLastBookLayout.setHorizontalGroup(
            jPanelSummaryLastBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(summaryLastBook1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        jPanelSummaryLastBookLayout.setVerticalGroup(
            jPanelSummaryLastBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(summaryLastBook1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        contenedorSup.add(jPanelSummaryLastBook);

        contenedorPrincipal.add(contenedorSup);

        contenedorInf.setViewportView(sugerenciasLibros1);

        contenedorPrincipal.add(contenedorInf);

        jButtonUsuario.setBackground(new java.awt.Color(69, 54, 55));
        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/UsuarioUL.png"))); // NOI18N
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        jButtonBiblioteca.setBackground(new java.awt.Color(69, 54, 55));
        jButtonBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/BibliotecaUL.png"))); // NOI18N

        jButtonTienda.setBackground(new java.awt.Color(69, 54, 55));
        jButtonTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TiendaUL.png"))); // NOI18N

        jDesktopPane1.setLayer(jButtonCerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonMinimizarUL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCerrarUL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(contenedorPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonBiblioteca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonTienda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMinimizarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMinimizarUL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCerrarUL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonMinimizarULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarULActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
        
    }//GEN-LAST:event_jButtonMinimizarULActionPerformed

    private void jButtonCerrarULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarULActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarULActionPerformed

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowDeiconified

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        // TODO add your handling code here:
        UserInfoUL objUserInfo = new UserInfoUL();
        objUserInfo.setVisible(true);
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contenedorInf;
    private vista.TransparentPanel contenedorPrincipal;
    private javax.swing.JPanel contenedorSup;
    private javax.swing.JButton jButtonBiblioteca;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonCerrarUL;
    private javax.swing.JButton jButtonMinimizarUL;
    private javax.swing.JButton jButtonTienda;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanelSummaryLastBook;
    private javax.swing.JPanel jPanelSummaryUser;
    private vista.SugerenciasLibros sugerenciasLibros1;
    private vista.SummaryBook summaryBook1;
    private vista.SummaryLastBook summaryLastBook1;
    private vista.SummaryUserUL summaryUserUL1;
    // End of variables declaration//GEN-END:variables
}
