/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.SwingConstants;
import tipografia.Fuente;

/**
 *
 * @author JhonCarlos
 */
public class UserInfoUL extends javax.swing.JFrame {
    Color transparencia;
    Fuente garamondRegular, verdanaRegular, verdanaBold;

    /**
     * Creates new form UserInfoUL
     */
    public UserInfoUL() {
        initComponents();
        
        //Posición
        this.setLocationRelativeTo(null);
        
        //Forma redondeada
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,27,27);
        AWTUtilities.setWindowShape(this, forma);
        
        this.transparencia = new Color(0,0,0,0);
        
        this.jPanelContenedorPrincipal.setBorder(new Background(0));
        this.jPanelContenedorSecundario.setBackground(transparencia);
        this.jPanelContenedorInfo.setBackground(transparencia);
        this.jPanel1.setBackground(transparencia);
        this.jPanel2.setBackground(transparencia);
        
        //Centrar imagen de jPanel
        this.jLabelImgPerfil.setHorizontalAlignment(SwingConstants.CENTER);
        this.jLabelImgPerfil.setVerticalAlignment(SwingConstants.CENTER);
        
        establecerFuentes();
        
    }
    
    public void establecerFuentes(){
        garamondRegular = new Fuente(3);
        verdanaRegular = new Fuente(4);
        verdanaBold = new Fuente(5);
        
        //Indicadores de macrocampos
        this.jLabelIndMacro1.setFont(garamondRegular.fuenteAgregar(18f));
        this.jLabelIndMacro2.setFont(garamondRegular.fuenteAgregar(18f));
        this.jLabelIndMacro3.setFont(garamondRegular.fuenteAgregar(18f));
        this.jLabelIndMacro4.setFont(garamondRegular.fuenteAgregar(18f));
        this.jLabelIndMacro5.setFont(garamondRegular.fuenteAgregar(18f));
        
        //Indicadores específicos
        this.jLabelInd1.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd2.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd3.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd4.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd5.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd6.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd7.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd8.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd9.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd10.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd11.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd12.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd13.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd14.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd15.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd16.setFont(verdanaBold.fuenteAgregar(12f));
        this.jLabelInd17.setFont(verdanaBold.fuenteAgregar(12f));
        
        //Campos a definir
        this.jLabelNombre.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelApellido.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelEdad.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelCumple.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelCelular.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelCorreo.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelLibrosCompletados.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelLibrosLeidos.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelLibrosAdquiridos.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelSaldo.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelUltimaRecarga.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelFechaUltRec.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelHoraUltRec.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelSesionesIniciadas.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelFechaUltSes.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelHoraUltSes.setFont(verdanaRegular.fuenteAgregar(12f));
        this.jLabelTiempoConexion.setFont(verdanaRegular.fuenteAgregar(12f));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedorPrincipal = new javax.swing.JPanel();
        jButtonMinimizarUL = new javax.swing.JButton();
        jButtonCerrarUL = new javax.swing.JButton();
        jPanelContenedorSecundario = new javax.swing.JPanel();
        jLabelImgPerfil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenedorInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIndMacro1 = new javax.swing.JLabel();
        jLabelInd1 = new javax.swing.JLabel();
        jLabelInd2 = new javax.swing.JLabel();
        jLabelInd3 = new javax.swing.JLabel();
        jLabelInd4 = new javax.swing.JLabel();
        jButtonModificarPersonales = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelIndMacro2 = new javax.swing.JLabel();
        jLabelInd5 = new javax.swing.JLabel();
        jLabelInd6 = new javax.swing.JLabel();
        jButtonModificarContacto = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelIndMacro3 = new javax.swing.JLabel();
        jLabelInd7 = new javax.swing.JLabel();
        jLabelInd8 = new javax.swing.JLabel();
        jLabelInd9 = new javax.swing.JLabel();
        jLabelCumple = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelLibrosCompletados = new javax.swing.JLabel();
        jLabelLibrosLeidos = new javax.swing.JLabel();
        jLabelLibrosAdquiridos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelIndMacro4 = new javax.swing.JLabel();
        jLabelIndMacro5 = new javax.swing.JLabel();
        jLabelInd10 = new javax.swing.JLabel();
        jLabelInd11 = new javax.swing.JLabel();
        jLabelInd12 = new javax.swing.JLabel();
        jLabelInd13 = new javax.swing.JLabel();
        jButtonRecargar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelInd14 = new javax.swing.JLabel();
        jLabelInd15 = new javax.swing.JLabel();
        jLabelInd16 = new javax.swing.JLabel();
        jLabelInd17 = new javax.swing.JLabel();
        jLabelUltimaRecarga = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelFechaUltRec = new javax.swing.JLabel();
        jLabelHoraUltRec = new javax.swing.JLabel();
        jLabelFechaUltSes = new javax.swing.JLabel();
        jLabelSesionesIniciadas = new javax.swing.JLabel();
        jLabelHoraUltSes = new javax.swing.JLabel();
        jLabelTiempoConexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelContenedorPrincipal.setBackground(new java.awt.Color(69, 54, 55));

        jButtonMinimizarUL.setBackground(new java.awt.Color(69, 54, 55));
        jButtonMinimizarUL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonMinimizarUL.setForeground(new java.awt.Color(201, 178, 169));
        jButtonMinimizarUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/MinimizarUL.png"))); // NOI18N
        jButtonMinimizarUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarULActionPerformed(evt);
            }
        });

        jButtonCerrarUL.setBackground(new java.awt.Color(69, 54, 55));
        jButtonCerrarUL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonCerrarUL.setForeground(new java.awt.Color(201, 178, 169));
        jButtonCerrarUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CerrarUL.png"))); // NOI18N
        jButtonCerrarUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarULActionPerformed(evt);
            }
        });

        jPanelContenedorSecundario.setBackground(new java.awt.Color(69, 54, 55));

        jLabelImgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PerfilUL.png"))); // NOI18N

        jPanelContenedorInfo.setBackground(new java.awt.Color(69, 54, 55));
        jPanelContenedorInfo.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel1.setBackground(new java.awt.Color(69, 54, 55));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(125, 108, 127), new java.awt.Color(125, 108, 127)));

        jLabelIndMacro1.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jLabelIndMacro1.setForeground(new java.awt.Color(229, 229, 229));
        jLabelIndMacro1.setText("Datos Personales");

        jLabelInd1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd1.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd1.setText("Nombre:");

        jLabelInd2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd2.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd2.setText("Apellido:");

        jLabelInd3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd3.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd3.setText("Edad:");

        jLabelInd4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd4.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd4.setText("Cumpleaños:");

        jButtonModificarPersonales.setBackground(new java.awt.Color(69, 54, 55));
        jButtonModificarPersonales.setForeground(new java.awt.Color(229, 229, 229));
        jButtonModificarPersonales.setText("Modificar Datos Personales");
        jButtonModificarPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPersonalesActionPerformed(evt);
            }
        });

        jLabelIndMacro2.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jLabelIndMacro2.setForeground(new java.awt.Color(229, 229, 229));
        jLabelIndMacro2.setText("Datos de Contacto");

        jLabelInd5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd5.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd5.setText("Celular:");

        jLabelInd6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd6.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd6.setText("E-Mail:");

        jButtonModificarContacto.setBackground(new java.awt.Color(69, 54, 55));
        jButtonModificarContacto.setForeground(new java.awt.Color(229, 229, 229));
        jButtonModificarContacto.setText("Modificar Datos de Contacto");
        jButtonModificarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarContactoActionPerformed(evt);
            }
        });

        jLabelIndMacro3.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jLabelIndMacro3.setForeground(new java.awt.Color(229, 229, 229));
        jLabelIndMacro3.setText("Biblioteca");

        jLabelInd7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd7.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd7.setText("Libros Completados:");

        jLabelInd8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd8.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd8.setText("% Libros Leídos:");

        jLabelInd9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd9.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd9.setText("Libros Adquiridos:");

        jLabelCumple.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCumple.setForeground(new java.awt.Color(229, 229, 229));
        jLabelCumple.setText("(Fecha de Cumpleaños)");

        jLabelEdad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(229, 229, 229));
        jLabelEdad.setText("(Edad)");

        jLabelApellido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(229, 229, 229));
        jLabelApellido.setText("(Apellido)");

        jLabelNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(229, 229, 229));
        jLabelNombre.setText("(Nombre)");

        jLabelCelular.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(229, 229, 229));
        jLabelCelular.setText("(Celular)");

        jLabelCorreo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(229, 229, 229));
        jLabelCorreo.setText("(Correo)");

        jLabelLibrosCompletados.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLibrosCompletados.setForeground(new java.awt.Color(229, 229, 229));
        jLabelLibrosCompletados.setText("(Número)");

        jLabelLibrosLeidos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLibrosLeidos.setForeground(new java.awt.Color(229, 229, 229));
        jLabelLibrosLeidos.setText("(Número)");

        jLabelLibrosAdquiridos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLibrosAdquiridos.setForeground(new java.awt.Color(229, 229, 229));
        jLabelLibrosAdquiridos.setText("(Número)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificarPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jButtonModificarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCumple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd3)
                        .addGap(66, 66, 66)
                        .addComponent(jLabelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd2)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd1)
                        .addGap(46, 46, 46)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInd6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInd7)
                            .addComponent(jLabelIndMacro1)
                            .addComponent(jLabelIndMacro2)
                            .addComponent(jLabelIndMacro3)
                            .addComponent(jLabelInd8)
                            .addComponent(jLabelInd9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLibrosCompletados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLibrosLeidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLibrosAdquiridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIndMacro1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd1)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd2)
                    .addComponent(jLabelApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd3)
                    .addComponent(jLabelEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd4)
                    .addComponent(jLabelCumple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificarPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndMacro2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd5)
                    .addComponent(jLabelCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd6)
                    .addComponent(jLabelCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificarContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndMacro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd7)
                    .addComponent(jLabelLibrosCompletados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd8)
                    .addComponent(jLabelLibrosLeidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd9)
                    .addComponent(jLabelLibrosAdquiridos))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelContenedorInfo.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(69, 54, 55));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(125, 108, 127), new java.awt.Color(125, 108, 127)));

        jLabelIndMacro4.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jLabelIndMacro4.setForeground(new java.awt.Color(229, 229, 229));
        jLabelIndMacro4.setText("Conexión");

        jLabelIndMacro5.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 18)); // NOI18N
        jLabelIndMacro5.setForeground(new java.awt.Color(229, 229, 229));
        jLabelIndMacro5.setText("Mi Cuenta");

        jLabelInd10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd10.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd10.setText("Saldo:");

        jLabelInd11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd11.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd11.setText("Última Recarga:");

        jLabelInd12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd12.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd12.setText("Fecha Ult. Rec.:");

        jLabelInd13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd13.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd13.setText("Hora Ult. Rec.:");

        jButtonRecargar.setBackground(new java.awt.Color(69, 54, 55));
        jButtonRecargar.setForeground(new java.awt.Color(229, 229, 229));
        jButtonRecargar.setText("Recargar");
        jButtonRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecargarActionPerformed(evt);
            }
        });

        jLabelInd14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd14.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd14.setText("Sesiones Iniciadas:");

        jLabelInd15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd15.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd15.setText("Fecha Última Sesión:");

        jLabelInd16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd16.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd16.setText("Hora Última Sesión:");

        jLabelInd17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelInd17.setForeground(new java.awt.Color(229, 229, 229));
        jLabelInd17.setText("Tiempo de Conexión:");

        jLabelUltimaRecarga.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelUltimaRecarga.setForeground(new java.awt.Color(229, 229, 229));
        jLabelUltimaRecarga.setText("(Última Recarga)");

        jLabelSaldo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(229, 229, 229));
        jLabelSaldo.setText("(Saldo)");

        jLabelFechaUltRec.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelFechaUltRec.setForeground(new java.awt.Color(229, 229, 229));
        jLabelFechaUltRec.setText("(Fecha de Última Recarga)");

        jLabelHoraUltRec.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelHoraUltRec.setForeground(new java.awt.Color(229, 229, 229));
        jLabelHoraUltRec.setText("(Hora de Última Recarga)");

        jLabelFechaUltSes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelFechaUltSes.setForeground(new java.awt.Color(229, 229, 229));
        jLabelFechaUltSes.setText("(Fecha de Última Sesión)");

        jLabelSesionesIniciadas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelSesionesIniciadas.setForeground(new java.awt.Color(229, 229, 229));
        jLabelSesionesIniciadas.setText("(Sesiones Iniciadas)");

        jLabelHoraUltSes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelHoraUltSes.setForeground(new java.awt.Color(229, 229, 229));
        jLabelHoraUltSes.setText("(Hora de Última Sesión)");

        jLabelTiempoConexion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTiempoConexion.setForeground(new java.awt.Color(229, 229, 229));
        jLabelTiempoConexion.setText("(Tiempo de Última Sesión)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUltimaRecarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonRecargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd10)
                        .addGap(82, 82, 82)
                        .addComponent(jLabelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd12)
                        .addGap(21, 21, 21)
                        .addComponent(jLabelFechaUltRec, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd13)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelHoraUltRec, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIndMacro4)
                            .addComponent(jLabelIndMacro5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFechaUltSes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd14)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelSesionesIniciadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd16)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelHoraUltSes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInd17)
                        .addGap(19, 19, 19)
                        .addComponent(jLabelTiempoConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIndMacro5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd10)
                    .addComponent(jLabelSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd11)
                    .addComponent(jLabelUltimaRecarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd12)
                    .addComponent(jLabelFechaUltRec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd13)
                    .addComponent(jLabelHoraUltRec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRecargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndMacro4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd14)
                    .addComponent(jLabelSesionesIniciadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd15)
                    .addComponent(jLabelFechaUltSes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd16)
                    .addComponent(jLabelHoraUltSes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd17)
                    .addComponent(jLabelTiempoConexion))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanelContenedorInfo.add(jPanel2);

        javax.swing.GroupLayout jPanelContenedorSecundarioLayout = new javax.swing.GroupLayout(jPanelContenedorSecundario);
        jPanelContenedorSecundario.setLayout(jPanelContenedorSecundarioLayout);
        jPanelContenedorSecundarioLayout.setHorizontalGroup(
            jPanelContenedorSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelContenedorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImgPerfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanelContenedorSecundarioLayout.setVerticalGroup(
            jPanelContenedorSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImgPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenedorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelContenedorPrincipalLayout = new javax.swing.GroupLayout(jPanelContenedorPrincipal);
        jPanelContenedorPrincipal.setLayout(jPanelContenedorPrincipalLayout);
        jPanelContenedorPrincipalLayout.setHorizontalGroup(
            jPanelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelContenedorSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContenedorPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonMinimizarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelContenedorPrincipalLayout.setVerticalGroup(
            jPanelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCerrarUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMinimizarUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenedorSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizarULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarULActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarULActionPerformed

    private void jButtonCerrarULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarULActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarULActionPerformed

    private void jButtonModificarPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPersonalesActionPerformed
        // TODO add your handling code here:
        ModDatosPersonales objDatPer = new ModDatosPersonales();
        objDatPer.setVisible(true);
    }//GEN-LAST:event_jButtonModificarPersonalesActionPerformed

    private void jButtonModificarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarContactoActionPerformed
        // TODO add your handling code here:
        ModDatosContacto objDatCont = new ModDatosContacto();
        objDatCont.setVisible(true);
    }//GEN-LAST:event_jButtonModificarContactoActionPerformed

    private void jButtonRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecargarActionPerformed
        // TODO add your handling code here:
        AgregarRecarga objAddRec = new AgregarRecarga();
        objAddRec.setVisible(true);
    }//GEN-LAST:event_jButtonRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfoUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfoUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfoUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfoUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfoUL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarUL;
    private javax.swing.JButton jButtonMinimizarUL;
    private javax.swing.JButton jButtonModificarContacto;
    private javax.swing.JButton jButtonModificarPersonales;
    private javax.swing.JButton jButtonRecargar;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCumple;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFechaUltRec;
    private javax.swing.JLabel jLabelFechaUltSes;
    private javax.swing.JLabel jLabelHoraUltRec;
    private javax.swing.JLabel jLabelHoraUltSes;
    private javax.swing.JLabel jLabelImgPerfil;
    private javax.swing.JLabel jLabelInd1;
    private javax.swing.JLabel jLabelInd10;
    private javax.swing.JLabel jLabelInd11;
    private javax.swing.JLabel jLabelInd12;
    private javax.swing.JLabel jLabelInd13;
    private javax.swing.JLabel jLabelInd14;
    private javax.swing.JLabel jLabelInd15;
    private javax.swing.JLabel jLabelInd16;
    private javax.swing.JLabel jLabelInd17;
    private javax.swing.JLabel jLabelInd2;
    private javax.swing.JLabel jLabelInd3;
    private javax.swing.JLabel jLabelInd4;
    private javax.swing.JLabel jLabelInd5;
    private javax.swing.JLabel jLabelInd6;
    private javax.swing.JLabel jLabelInd7;
    private javax.swing.JLabel jLabelInd8;
    private javax.swing.JLabel jLabelInd9;
    private javax.swing.JLabel jLabelIndMacro1;
    private javax.swing.JLabel jLabelIndMacro2;
    private javax.swing.JLabel jLabelIndMacro3;
    private javax.swing.JLabel jLabelIndMacro4;
    private javax.swing.JLabel jLabelIndMacro5;
    private javax.swing.JLabel jLabelLibrosAdquiridos;
    private javax.swing.JLabel jLabelLibrosCompletados;
    private javax.swing.JLabel jLabelLibrosLeidos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSesionesIniciadas;
    private javax.swing.JLabel jLabelTiempoConexion;
    private javax.swing.JLabel jLabelUltimaRecarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContenedorInfo;
    private javax.swing.JPanel jPanelContenedorPrincipal;
    private javax.swing.JPanel jPanelContenedorSecundario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}

